# Design sources (that will be coppied into each work directory)
sources:
  path: examples/workflow_simple

# Progress tracking
progress:
  file: progress.txt
  regex: ".*Progress: ([0-9]+)*"

# Generated design settings
use_parameters: Yes
param_target_file: "main.py" # this is the file in which the parameters will be replaced
start_delimiter: 'AWESOME_STRING = "'
stop_delimiter: '"'

# Design workflow settings
tasks:
  - name: main
    dependencies: 
      - "generate_config"
    commands:
      - echo 'Generating string...'
      - sleep 1
      - echo 'step 1/3 done'
      - "echo 'Progress: 60' > progress.txt"
      - sleep 1
      - echo 'step 2/3 done'
      - "echo 'Progress: 80' > progress.txt"
      - sleep 1
      - echo 'step 3/3 done'
      - "echo 'Progress: 100' > progress.txt"

  - name: "generate_config"
    commands:
      - echo 'Generating config.txt...'
      - sleep 1
      - echo 'step 1/2 done'
      - "echo 'Progress: 20' > progress.txt"
      - sleep 1
      - echo 'step 2/2 done'
      - "echo 'Progress: 40' > progress.txt"
      - touch config.txt
