# Required
version: 2

# Git submodules
submodules:
  include: all
  recursive: true

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  apt_packages:
    - hugo

  commands:
    - hugo --source docs --destination $READTHEDOCS_OUTPUT/html
