# Required
version: 2

# Git submodules
submodules:
  include: all
  recursive: true

build:
  os: ubuntu-26.04
  tools:
    python: "3.12"
    hugo: "0.154.5"

  commands:
    - hugo --source docs --destination $READTHEDOCS_OUTPUT/html
