# ********************************************************************** #
#                                Odatix                                  #
# ********************************************************************** #
#
# Copyright (C) 2022 Jonathan Saussereau
#
# This file is part of Odatix.
# Odatix is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Odatix is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#

"""
The space a search moves through, and how a place in it becomes something to
run.

Nothing new is described here. An architecture already says what its parameters
are, and a search reads the very same thing the sweep enumerates: the
:class:`~odatix.workspace.space.ParameterSpace` of each of its parameter
domains, physical (a directory of configurations, or the rules that describe
them) and virtual alike (a variable substituted into the commands, which has no
directory but is an axis all the same -- and, for a design generated by
high-level synthesis, usually *the* axis worth searching).

The difference between sweeping and searching is only that a search picks its
points instead of taking them all, which is what
:meth:`ParameterSpace.axes` and :meth:`ConfigSet.resolve_point` are for.

A place in the space is a *genome*: one number per axis, saying which of the
values of that axis this design uses. It is a flat tuple of integers because
that is what a search operates on -- two designs are crossed by taking some
numbers from one and some from the other, and mutated by moving one of them --
and it is turned back into the "<architecture>/<configuration>" a run selects
only when a design is about to be evaluated.
"""

import itertools

import odatix.lib.hard_settings as hard_settings
from odatix.lib.config_generator import get_variables
from odatix.lib.virtual_param_domain import sanitize_value
from odatix.workspace.attributes import read_value
from odatix.workspace.exclusions import ExclusionSet, context as exclusion_context
from odatix.workspace.space import Axis, ParameterSpace, config_set_rules

__all__ = [
    "SearchAxis",
    "DomainSpace",
    "VirtualDomainSpace",
    "FrequencySpace",
    "Toolchain",
    "ToolchainSpace",
    "toolchains_for",
    "ArchitectureSpace",
    "Design",
    "DomainSelection",
    "EmptySpaceError",
    "UnknownConfigurationError",
    "UnknownToolchainError",
    "MAIN_DOMAIN",
]

MAIN_DOMAIN = hard_settings.main_parameter_domain


class EmptySpaceError(ValueError):
    """
    An architecture offers a search nothing to choose from.

    Either it declares no parameters at all, or every one of its domains holds
    a single configuration: there is one design to run, and running it is a
    sweep of one, not a search.
    """


class SearchAxis(object):
    """
    One choice a design makes, and where that choice comes from.

    Wraps an :class:`~odatix.workspace.space.Axis` with the domain it belongs
    to, so that a genome can be read back as something a user recognizes.
    """

    __slots__ = ("domain", "axis", "kind")

    #: A variable (or a group of paired variables) of a domain that describes
    #: its configurations with rules.
    VARIABLE = "variable"
    #: The domain itself: it holds configuration files and nothing says how they
    #: relate, so the only choice is which one to use.
    CONFIGURATION = "configuration"
    #: A variable substituted into the commands of the architecture.
    VIRTUAL = "virtual"
    #: The frequency a custom frequency synthesis runs at. Not a parameter of
    #: the design at all -- the same design at two frequencies is the same
    #: hardware -- but a choice the search makes all the same.
    FREQUENCY = "frequency"
    #: What runs the design: an eda tool, one of its flows, one of its targets.
    #: Not a parameter of the design either, and the three of them are a single
    #: axis because they are not independent -- a flow belongs to a tool, and so
    #: does a target (see :class:`ToolchainSpace`).
    TOOLCHAIN = "toolchain"

    def __init__(self, domain, axis, kind=VARIABLE):
        self.domain = domain
        self.axis = axis
        self.kind = kind

    @property
    def label(self):
        """How the axis is named to a user."""
        if self.kind == SearchAxis.CONFIGURATION:
            return "configuration" if self.domain == MAIN_DOMAIN else self.domain
        if self.domain == MAIN_DOMAIN or self.kind in (
            SearchAxis.VIRTUAL, SearchAxis.FREQUENCY, SearchAxis.TOOLCHAIN
        ):
            return self.axis.label
        return "{0}.{1}".format(self.domain, self.axis.label)

    def __len__(self):
        return len(self.axis)

    def __repr__(self):
        return "<SearchAxis {0} ({1} values)>".format(self.label, len(self))


class DomainSpace(object):
    """
    What one parameter domain of an architecture offers a search.

    A domain that describes its configurations with rules offers its variables:
    a search can move along each of them, and the configuration a set of values
    stands for is resolved on the spot, without the rest of the domain having
    been generated. A domain holding only files offers the files -- there is
    nothing to move along, so the choice is which configuration to use.
    """

    def __init__(self, name, config_set):
        self.name = name
        self.config_set = config_set
        #: What is written in the hand-written configurations of this domain,
        #: read once and only when an exclusion asks for it.
        self._files = None
        #: Which choice names each configuration, built the first time an
        #: exclusion pins this domain to one of them.
        self._choices = None
        space = config_set.space
        if space.generates and space.valid and space.axes():
            self.kind = SearchAxis.VARIABLE
            self.axes = [SearchAxis(name, axis, SearchAxis.VARIABLE) for axis in space.axes()]
        else:
            self.kind = SearchAxis.CONFIGURATION
            names = config_set.names()
            rows = [{name: value} for value in names]
            self.axes = [SearchAxis(name, Axis([name], rows), SearchAxis.CONFIGURATION)] if names else []

    def configurations(self, choice):
        """
        What one choice per axis of this domain contributes to a design.

        Returns:
            tuple: ``{domain: configuration}`` and ``{variable: value}``, or
            (None, {}) when the choice names nothing runnable -- a
            configuration the domain blacklists, or a combination its
            constraints rule out.
        """
        chosen, values, _contents = self.resolve(choice)
        return chosen, values

    def resolve(self, choice):
        """
        The same thing, plus what is written in the configuration.

        The content is what an ``attributes`` block reads when the name does not
        say enough (see :mod:`odatix.workspace.attributes`), which is the case a
        hand-written domain is in.

        Returns:
            tuple: ``{domain: configuration}``, ``{variable: value}`` and
            ``{domain: content}``.
        """
        if self.kind == SearchAxis.CONFIGURATION:
            if not self.axes:
                return None, {}, {}
            row = self.axes[0].axis.rows[choice[0] % len(self.axes[0])]
            name = list(row.values())[0]
            return {self.name: name}, {}, {self.name: self.content_of(name)}

        assignment = {}
        for axis, index in zip(self.axes, choice):
            assignment.update(axis.axis.rows[index % len(axis)])
        resolved = self.config_set.resolve_point(assignment)
        if resolved is None:
            return None, {}, {}
        return {self.name: resolved.name}, dict(resolved.values), {self.name: resolved.content}

    def choice_for(self, name):
        """
        Which choice of this domain names a given configuration, or None when
        none does.

        A domain holding files answers with the row of that file. A domain
        described by rules has to look: a name is what its rules *produce*, and
        the only honest way back is to ask each of its points what it is called.
        The domains this is asked of are the ones an exclusion pins, so the
        answer is worth building once and keeping.
        """
        name = str(name)
        if self.kind == SearchAxis.CONFIGURATION:
            if not self.axes:
                return None
            axis = self.axes[0]
            for index, row in enumerate(axis.axis.rows):
                if str(list(row.values())[0]) == name:
                    return (index,)
            return None

        if self._choices is None:
            self._choices = {}
            for choice in itertools.product(*[range(len(axis)) for axis in self.axes]):
                chosen, _values, _contents = self.resolve(choice)
                if chosen is None:
                    continue
                self._choices.setdefault(str(chosen[self.name]), choice)
        return self._choices.get(name)

    def content_of(self, name):
        """What is written in one configuration of this domain, read once."""
        if self._files is None:
            self._files = self.config_set.files()
        return self._files.get(name, "")

    def __repr__(self):
        return "<DomainSpace {0} ({1} axes)>".format(self.name, len(self.axes))


class VirtualDomainSpace(object):
    """
    What the variables of an architecture offer a search when they feed its
    commands rather than its sources.

    Those are the "virtual parameter domains" (see
    :mod:`odatix.lib.virtual_param_domain`): a variable with no directory and no
    configuration file, whose value is substituted into the generation command
    and which still expands into one job per value. A design generated by
    high-level synthesis has all of its knobs there -- the number of taps of a
    filter, the initiation interval a loop is pipelined at -- so an exploration
    that could not search them would miss the case it is most needed for.

    They are read through the very same rendering the sweep uses, so that a
    value is spelled here exactly as it is spelled in the directory the job runs
    in: what a search proposes has to be what the results file will call it.
    """

    def __init__(self, variables, source=""):
        self.variables = dict(variables or {})
        self.names = [name for name in self.variables if str(name).strip()]
        # The same synthetic rules build_variants() builds: one line per
        # variable, so that rendering a point gives back each value formatted
        # the way the job directory will spell it.
        self.space = ParameterSpace(
            self.variables,
            name="__virtual__" + "__".join("${" + name + "}" for name in self.names),
            template="\n".join("{0}: ${{{0}}}".format(name) for name in self.names),
            source=source,
        )
        self.axes = [SearchAxis("", axis, SearchAxis.VIRTUAL) for axis in self.space.axes()]

    def configurations(self, choice):
        """One selection segment per variable, spelled as a job directory is."""
        chosen, values, _contents = self.resolve(choice)
        return chosen, values

    def resolve(self, choice):
        """The same thing, with no content to read: a variable has no file."""
        import yaml

        assignment = {}
        for axis, index in zip(self.axes, choice):
            assignment.update(axis.axis.rows[index % len(axis)])
        point = self.space.point(assignment)
        if point is None:
            return None, {}, {}

        try:
            rendered = yaml.load(point.content, Loader=yaml.loader.BaseLoader)
        except yaml.YAMLError:
            return None, {}, {}
        if not isinstance(rendered, dict):
            return None, {}, {}

        configurations = {}
        for name in self.names:
            value = rendered.get(name, "")
            value = str(value).strip() if value is not None else ""
            declaration = self.variables.get(name, {})
            unit = str(declaration.get("unit", "") or "") if isinstance(declaration, dict) else ""
            configurations[name] = sanitize_value(value + unit)
        return configurations, dict(point.values), {}

    def __repr__(self):
        return "<VirtualDomainSpace {0}>".format(", ".join(self.names))


class FrequencySpace(object):
    """
    The frequency a custom frequency synthesis runs a design at, when the
    search is the one choosing it.

    It is not a parameter of the architecture: nothing in its sources changes
    with it, and two designs that differ only by it are the same hardware told
    to go at a different speed. It is an axis all the same -- the trade-off a
    custom frequency synthesis is run for *is* the one between the frequency
    asked for and what the design costs at it -- so a search that could not move
    along it would only ever compare designs at whatever frequency it was
    handed.
    """

    #: Not a parameter domain: the name is only what keeps it apart from one.
    name = "__frequency__"

    def __init__(self, frequencies):
        self.frequencies = [int(value) for value in frequencies or []]
        rows = [{SearchAxis.FREQUENCY: value} for value in self.frequencies]
        self.axes = [SearchAxis("", Axis([SearchAxis.FREQUENCY], rows), SearchAxis.FREQUENCY)] if rows else []

    def frequency(self, choice):
        """The frequency one choice stands for, in MHz."""
        if not self.axes:
            return None
        return self.frequencies[choice[0] % len(self.frequencies)]

    def __repr__(self):
        return "<FrequencySpace ({0} frequencies)>".format(len(self.frequencies))


class UnknownToolchainError(ValueError):
    """An exploration names an eda tool, a flow or a target that does not exist."""


class Toolchain(object):
    """
    What runs a design: an eda tool, one of its flows, one of its targets.

    The three travel together because they are not independent -- a flow is
    declared by a tool and a target is enabled by one -- so "vivado with the
    power_opt flow on xc7a100t" is one choice, not three.

    A flow or a target left empty means "whatever the workspace already runs":
    the default flow of the tool, and every target its target file enables. That
    is what a toolchain nobody is searching looks like, and it is what keeps an
    exploration that says nothing about them running exactly as it did before.
    """

    __slots__ = ("tool", "flow", "target")

    def __init__(self, tool, flow="", target=""):
        self.tool = str(tool or "")
        self.flow = str(flow or "")
        self.target = str(target or "")

    @property
    def key(self):
        """What tells two toolchains apart, as something hashable."""
        return (self.tool, self.flow, self.target)

    @property
    def label(self):
        """How the toolchain is named to a user."""
        label = self.tool
        if self.flow:
            label += "@" + self.flow
        if self.target:
            label += " on " + self.target
        return label

    def slug(self):
        """The toolchain as a piece of a file name."""
        return "_".join(part for part in (self.tool, self.flow, self.target) if part) or "run"

    def to_dict(self):
        record = {"tool": self.tool}
        if self.flow:
            record["flow"] = self.flow
        if self.target:
            record["target"] = self.target
        return record

    def __repr__(self):
        return "<Toolchain {0}>".format(self.label)

    def __eq__(self, other):
        if not isinstance(other, Toolchain):
            return NotImplemented
        return self.key == other.key

    def __ne__(self, other):
        result = self.__eq__(other)
        return result if result is NotImplemented else not result

    def __hash__(self):
        return hash(self.key)


def toolchains_for(workspace, tools, flows=(), targets=()):
    """
    Every toolchain an exploration is allowed to run a design with.

    The tools, the flows and the targets are each either one name -- fixed, the
    same for every design -- or several, which the search then chooses between.
    They are combined, but not blindly: a flow named for one tool and declared
    by another would be a combination that cannot run, so every combination is
    checked against what the workspace holds and the ones that do not exist are
    left out rather than proposed and failed hours later.

    Args:
        workspace (Workspace): where the tools, their flows and their targets
            are read from.
        tools (list): the eda tools, one of which runs each design.
        flows (list): their flows, empty for the default flow of each tool.
        targets (list): their targets, empty for every target each tool enables.

    Returns:
        list: the toolchains, in the order they were named.

    Raises:
        UnknownToolchainError: a tool that does not exist was named, or a flow
            or a target no named tool has.
    """
    from odatix.workspace.errors import NotFoundError

    tools = [str(name).strip() for name in (tools or []) if str(name).strip()]
    flows = [str(name).strip() for name in (flows or []) if str(name).strip()]
    targets = [str(name).strip() for name in (targets or []) if str(name).strip()]
    if not tools:
        return []

    combinations = []
    unused_flows = set(flows)
    unused_targets = set(targets)
    for tool_name in tools:
        try:
            tool = workspace.tools[tool_name]
        except NotFoundError:
            raise UnknownToolchainError(
                "The exploration runs with an eda tool that does not exist: \"{0}\". "
                "Available tools are: {1}.".format(tool_name, ", ".join(workspace.tools.all_names()))
            )

        declared = tool.effective_settings.flow_names()
        # A tool whose flow is not being searched runs whichever one it runs by
        # itself, and is not asked to name it.
        tool_flows = [name for name in flows if name in declared] if flows else [""]
        for name in tool_flows:
            unused_flows.discard(name)

        enabled = tool.targets.enabled_names()
        tool_targets = [name for name in targets if name in enabled] if targets else [""]
        for name in tool_targets:
            unused_targets.discard(name)

        for flow_name in tool_flows:
            for target_name in tool_targets:
                combinations.append(Toolchain(tool_name, flow_name, target_name))

    if unused_flows:
        raise UnknownToolchainError(
            "The exploration runs flow(s) no eda tool it uses declares: {0}. The flows of {1} are: "
            "{2}.".format(
                ", ".join(sorted(unused_flows)), ", ".join(tools),
                ", ".join(sorted(set(
                    name for tool_name in tools
                    for name in workspace.tools[tool_name].effective_settings.flow_names()
                ))),
            )
        )
    if unused_targets:
        raise UnknownToolchainError(
            "The exploration runs on target(s) no eda tool it uses enables: {0}. The enabled targets "
            "of {1} are: {2}.".format(
                ", ".join(sorted(unused_targets)), ", ".join(tools),
                ", ".join(sorted(set(
                    name for tool_name in tools
                    for name in workspace.tools[tool_name].targets.enabled_names()
                ))) or "none",
            )
        )
    return combinations


class ToolchainSpace(object):
    """
    What runs a design, when the search is the one choosing it.

    Like the frequency, this is not a parameter of the architecture: the same
    design synthesized by two tools, by two flows of one tool or for two targets
    is the same rtl. It is a choice worth searching all the same -- what a
    design costs is as much a property of what built it as of what it is -- and
    it is the whole point of an exploration that asks "which target is this
    design cheapest on".

    The three of them are *one* axis rather than three, because a flow and a
    target belong to a tool: crossing them freely would keep proposing
    combinations no workspace can run. What the axis holds is the combinations
    that do exist (see :func:`toolchains_for`).
    """

    #: Not a parameter domain: the name is only what keeps it apart from one.
    name = "__toolchain__"

    def __init__(self, toolchains):
        self.toolchains = list(toolchains or [])
        rows = [{SearchAxis.TOOLCHAIN: chain.label} for chain in self.toolchains]
        # One value is a fixed toolchain, not a choice: it is what every design
        # runs with, and there is nothing for the search to move along.
        self.axes = (
            [SearchAxis("", Axis([SearchAxis.TOOLCHAIN], rows), SearchAxis.TOOLCHAIN)]
            if len(rows) > 1 else []
        )

    def toolchain(self, choice):
        """The toolchain one choice stands for."""
        if not self.axes:
            return self.toolchains[0] if self.toolchains else None
        return self.toolchains[choice[0] % len(self.toolchains)]

    def __repr__(self):
        return "<ToolchainSpace ({0} toolchains)>".format(len(self.toolchains))


class UnknownConfigurationError(ValueError):
    """A selection fixes a domain to a configuration the architecture has not."""


class DomainSelection(object):
    """
    What an entry of "architectures" says about the domains of an architecture.

    An exploration selects what it searches the way every run selects what it
    runs (see :mod:`odatix.workspace.selection`), because that is what a user
    already writes::

        AsteRISC                          search every domain
        AsteRISC/*                        the same thing, said out loud
        AsteRISC/* + Mul/*                the main domain and "Mul", and those two only
        AsteRISC/* + MEM/1024I + Mul/*    with "MEM" fixed to one configuration

    A domain written "<domain>/*" is searched, one written "<domain>/<name>" is
    fixed to that configuration for every design, and one that is not written at
    all is left out of the designs entirely -- exactly what running that same
    entry with "odatix fmax" would do. An entry that names no domain at all says
    nothing about them, so all of them are searched.
    """

    def __init__(self, entry="", main="*", pins=None, searched=(), mentioned=()):
        #: The architecture the entry names.
        self.entry = entry
        #: What the main domain is fixed to, "*" when it is searched.
        self.main = main
        self.pins = dict(pins or {})
        self.searched = set(searched)
        #: The other domains the entry names, searched or fixed.
        self.mentioned = set(mentioned)

    @staticmethod
    def parse(text):
        """Read one entry of the "architectures" of an exploration."""
        from odatix.workspace.selection import parse as parse_entry

        request = parse_entry(text, keep_extension_note=False)
        pins = {}
        searched = set()
        mentioned = set()
        main = request.configuration if request.has_configuration else "*"
        if main != "*":
            pins[MAIN_DOMAIN] = main
        for selector in request.domains:
            domain, _, value = selector.partition("/")
            if not domain:
                continue
            mentioned.add(domain)
            if value in ("", "*"):
                searched.add(domain)
            else:
                pins[domain] = value
        return DomainSelection(
            entry=request.entry, main=main, pins=pins, searched=searched, mentioned=mentioned
        )

    ######################################
    # What it says about one domain
    ######################################

    def searches(self, name):
        """Whether the search chooses the configuration of this domain."""
        if name == MAIN_DOMAIN:
            return self.main == "*"
        if not self.mentioned:
            return True
        return name in self.searched

    def holds(self, name):
        """Whether this domain is fixed to one configuration."""
        return name in self.pins

    def check(self, domain):
        """
        The configuration this domain is fixed to, checked against what it holds.

        Raises:
            UnknownConfigurationError: it holds no such configuration.
        """
        value = self.pins[domain.name]
        names = domain.configuration_names()
        if names and value not in names:
            raise UnknownConfigurationError(
                "\"{0}\" has no configuration \"{1}\" in its \"{2}\" parameter domain. "
                "It holds: {3}.".format(self.entry, value, domain.name, ", ".join(names))
            )
        return value

    def check_domains(self, architecture):
        """
        Make sure every domain the entry names is one the architecture has: a
        misspelled domain would otherwise silently narrow the search instead of
        being reported.

        Raises:
            UnknownConfigurationError: the entry names a domain that is not there.
        """
        existing = set(domain.name for domain in architecture.domains)
        unknown = sorted(self.mentioned - existing)
        if unknown:
            raise UnknownConfigurationError(
                "\"{0}\" has no parameter domain named {1}. It has: {2}.".format(
                    architecture.name,
                    ", ".join("\"{0}\"".format(name) for name in unknown),
                    ", ".join(sorted(name for name in existing if name != MAIN_DOMAIN)) or "none",
                )
            )
        return self

    ######################################
    # How it is named
    ######################################

    def describe(self):
        """The entry as it was written, without its spaces."""
        parts = ["{0}/{1}".format(self.entry, self.main)]
        for domain in sorted(self.mentioned):
            parts.append("{0}/{1}".format(domain, self.pins.get(domain, "*")))
        return "+".join(parts)

    @property
    def slug(self):
        """
        What tells two campaigns of the same architecture apart, in a filename.

        Searching an architecture with one domain fixed is not searching the
        same space as searching it with another, so the two cannot share an
        archive.
        """
        if not self.pins:
            return self.entry or ""
        name = self.entry
        if MAIN_DOMAIN in self.pins:
            name += "_" + self.pins[MAIN_DOMAIN]
        fixed = "_".join(
            "{0}_{1}".format(domain, self.pins[domain])
            for domain in sorted(self.pins) if domain != MAIN_DOMAIN
        )
        return "{0}+{1}".format(name, fixed) if fixed else name

    def __repr__(self):
        return "<DomainSelection {0}>".format(self.describe())


class ArchitectureSpace(object):
    """
    Everything a search may choose for one architecture: the axes of its
    parameter domains, then those of the variables its commands take.

    A campaign searches one architecture at a time. Two architectures do not
    have the same parameters, so crossing a design of one with a design of the
    other would mean nothing; asking for several is asking for several searches.
    """

    def __init__(self, architecture, frequencies=None, toolchains=None, selection=None,
                 exclusions=None):
        self.architecture = architecture
        self.name = architecture.name
        self.parts = []
        #: What the architecture says its design space does not hold, and what a
        #: campaign says on top of it (see
        #: :mod:`odatix.workspace.exclusions`). Read from the architecture when
        #: the caller passes nothing.
        self.exclusions = self._exclusions_of(architecture, exclusions)
        #: How the configurations of each domain are read beyond their name, so
        #: that an exclusion can be written about a hand-written one.
        self.attributes = self._attributes_of(architecture)
        #: The keys of "configurations" that are variables of the commands
        #: rather than parameter domains: they are values, and are read as such.
        self._virtual_keys = set()
        #: Where a pinned name lives in a genome, built on first use.
        self._pin_targets = None
        #: What the selection fixed: ``{domain: configuration}``. Those domains
        #: are part of every design of the space and are not searched.
        self.pinned = {}
        selection = selection if selection is not None else DomainSelection()
        self.selection = selection

        for domain in architecture.domains:
            # The same domains a sweep takes its axes from: one that substitutes
            # nothing, or that holds no configuration, adds no choice either.
            if not domain.use_parameters:
                continue
            if not selection.searches(domain.name):
                if selection.holds(domain.name):
                    self.pinned[domain.name] = selection.check(domain)
                continue
            part = DomainSpace(domain.name, domain.config_set)
            if part.axes:
                self.parts.append(part)
        selection.check_domains(architecture)

        virtual = self.virtual_domains()
        if virtual is not None and virtual.axes:
            self.parts.append(virtual)

        # Last, and in this order, so that adding either of them to a campaign
        # does not move the parameters around in the genomes an earlier archive
        # was written with.
        self.frequencies = FrequencySpace(frequencies)
        if self.frequencies.axes:
            self.parts.append(self.frequencies)

        #: What runs the designs. Always there, even when it is a single
        #: toolchain the search never chooses: a design has to know what ran it
        #: either way, since that is where its results are read from.
        self.toolchains = ToolchainSpace(toolchains)
        if self.toolchains.axes:
            self.parts.append(self.toolchains)

    @staticmethod
    def _exclusions_of(architecture, exclusions):
        """The exclusions of the architecture, plus what a campaign adds to them."""
        declared = None
        reader = getattr(architecture, "exclusions", None)
        if callable(reader):
            try:
                declared = reader()
            except Exception:
                declared = None
        if declared is None:
            return exclusions if exclusions is not None else ExclusionSet()
        return declared.merge(exclusions)

    @staticmethod
    def _attributes_of(architecture):
        found = {}
        try:
            found = dict(getattr(architecture, "attributes", {}) or {})
        except Exception:
            found = {}
        return found

    def virtual_domains(self):
        """
        The variables of the architecture, when they are axes of their own.

        They are, under exactly the condition
        :func:`~odatix.lib.virtual_param_domain.build_variants` applies: the
        settings file declares variables and does *not* use them to describe
        configurations. Otherwise the same variables are already an axis as the
        rules of the main domain, and reading them twice would search one axis
        as if it were two.
        """
        settings = self.architecture.settings.to_dict()
        if bool(settings.get("generate_configurations", False)):
            return None
        if config_set_rules(settings, source=self.architecture.settings_path).generates:
            return None
        variables, _legacy = get_variables(settings)
        if not variables:
            return None
        return VirtualDomainSpace(variables, source=self.architecture.settings_path)

    ######################################
    # The axes
    ######################################

    @property
    def axes(self):
        """Every axis of the architecture, in the order a genome holds them."""
        return [axis for part in self.parts for axis in part.axes]

    @property
    def lengths(self):
        """How many values each axis offers."""
        return [len(axis) for axis in self.axes]

    def size(self):
        """
        How many designs the space holds, counted rather than enumerated.

        A campaign prints it next to its budget, because the ratio between the
        two is the only reason to search rather than sweep.
        """
        total = 1
        for length in self.lengths:
            total *= length
        return total

    def require_choice(self):
        """
        Check that there is something to search, and say why when there is not.

        Raises:
            EmptySpaceError: the architecture offers a single design.
        """
        if self.size() <= 1:
            raise EmptySpaceError(
                "\"{0}\" holds {1} design: there is nothing to search. An exploration needs an "
                "architecture whose parameters describe several configurations -- run it with "
                "\"odatix fmax\" instead.".format(self.name, self.size())
            )
        return self

    ######################################
    # A place in it
    ######################################

    def genomes(self):
        """
        Every design of the space, in the order a sweep would run them.

        This is what makes an exhaustive exploration one strategy among the
        others rather than a separate mechanism.
        """
        return itertools.product(*[range(length) for length in self.lengths])

    def clamp(self, genome):
        """A genome brought back inside the space, whichever way it was built."""
        return tuple(int(gene) % length for gene, length in zip(genome, self.lengths))

    def split(self, genome):
        """The genome cut up into the choice each part of the space makes."""
        choices = []
        cursor = 0
        for part in self.parts:
            width = len(part.axes)
            choices.append(tuple(genome[cursor:cursor + width]))
            cursor += width
        return choices

    def design(self, genome, project=True):
        """
        What a genome stands for: the entry a run selects, and the parameters
        behind it.

        Args:
            genome (tuple): a place in the space.
            project (bool): move the genome to the design an exclusion says it
                should be, when it names one -- which is what keeps a
                ``duplicate`` from emptying the space instead of folding it (see
                :meth:`project`).

        Returns:
            Design: the design, or None when the genome names a configuration
            the architecture does not run -- one its domain blacklists, a
            combination the constraints of that domain rule out, or one its
            exclusions take out of the space.
        """
        genome = self.clamp(genome)
        built = self._build(genome)
        if built is None:
            return None

        excluded = self.excluded(built)
        if excluded is None:
            return built

        if project and excluded.pins:
            moved = self.project(genome, excluded.pins)
            if moved is not None and moved != genome:
                # Once: a projection that lands on another excluded point is a
                # point that is out, not a reason to keep moving.
                return self.design(moved, project=False)
        return None

    def _build(self, genome):
        """The design a genome stands for, before its exclusions are applied."""
        # What the selection fixed is part of every design: it is not searched,
        # but it is still what the run selects and where the results are read.
        configurations = dict(self.pinned)
        values = {}
        contents = {}
        frequency = None
        # What runs the design when the search is not the one choosing it.
        toolchain = self.toolchains.toolchain((0,))
        for part, choice in zip(self.parts, self.split(genome)):
            if isinstance(part, FrequencySpace):
                frequency = part.frequency(choice)
                continue
            if isinstance(part, ToolchainSpace):
                toolchain = part.toolchain(choice)
                continue
            chosen, assigned, written = part.resolve(choice)
            if chosen is None:
                return None
            configurations.update(chosen)
            contents.update(written)
            if isinstance(part, VirtualDomainSpace):
                self._virtual_keys.update(chosen)
            prefix = "" if getattr(part, "name", MAIN_DOMAIN) == MAIN_DOMAIN else part.name + "."
            for variable, value in assigned.items():
                values[prefix + variable] = value
        return Design(
            self.name, genome, configurations, values,
            frequency=frequency, toolchain=toolchain,
            chose_toolchain=bool(self.toolchains.axes),
            contents=contents,
        )

    ######################################
    # What the space does not hold
    ######################################

    def excluded(self, design):
        """
        Why one design is not part of the space, or None when it is.

        Returns:
            Excluded: the rule that rejects it, and what it would have it be
            instead.
        """
        if design is None or not len(self.exclusions):
            return None
        return self.exclusions.check(self.context(design))

    def context(self, design):
        """What the expressions of an exclusion read, for one design."""
        configurations = {
            domain: name for domain, name in design.configurations.items()
            if domain not in self._virtual_keys
        }
        return exclusion_context(
            self.name, configurations, design.values,
            attributes=self.attributes, contents=design.contents,
            main_domain=MAIN_DOMAIN,
            extra={"frequency": design.frequency} if design.frequency is not None else None,
        )

    def project(self, genome, pins):
        """
        The genome moved to the values an exclusion pins it to.

        A ``duplicate`` says which of several identical designs is the one to
        run. Folding the others onto it, rather than dropping them, is what
        keeps a search from spending its budget proposing points that do not
        exist -- and it is the honest answer, since they *are* that design.

        Args:
            genome (tuple): where the search wanted to go.
            pins (dict): ``{name: value}``, as an exclusion writes them.

        Returns:
            tuple: the genome moved, or None when nothing could be moved --
            the pin names something that is not an axis, or a value the axis
            does not offer.
        """
        moved = list(self.clamp(genome))
        for name, value in pins.items():
            name = str(name)
            target = self.pin_targets().get(name)
            if target is not None:
                position, variable, rows = target
                index = _row_index(rows, variable, value)
                if index is None:
                    return None
                moved[position] = index
                continue

            # Not a variable: a domain pinned to one of its configurations,
            # which is how a rule says "this one is the one to run".
            part = self.domain_parts().get(name)
            if part is None:
                return None
            choice = part.choice_for(value)
            if choice is None:
                return None
            start = self.position_of(part)
            for offset, index in enumerate(choice):
                moved[start + offset] = index
        return tuple(moved)

    def domain_parts(self):
        """The parts of the space that are parameter domains, by name."""
        found = {}
        for part in self.parts:
            if not isinstance(part, DomainSpace):
                continue
            name = getattr(part, "name", MAIN_DOMAIN)
            found[name] = part
            if name == MAIN_DOMAIN:
                # The names an exclusion calls the main domain by.
                found["config"] = part
                found["main"] = part
        return found

    def position_of(self, part):
        """Where the axes of one part start, in a genome."""
        position = 0
        for candidate in self.parts:
            if candidate is part:
                return position
            position += len(candidate.axes)
        return position

    def pin_targets(self):
        """
        Where each name an exclusion may pin lives in a genome:
        ``{name: (position, variable, rows)}``.

        A variable of the main domain is reachable by its bare name, one of
        another domain as "<domain>.<variable>", and a domain holding files by
        its own name -- which is exactly how an exclusion writes them.
        """
        if getattr(self, "_pin_targets", None) is not None:
            return self._pin_targets

        targets = {}
        position = 0
        for part in self.parts:
            domain = getattr(part, "name", MAIN_DOMAIN)
            for axis in part.axes:
                rows = axis.axis.rows
                for variable in axis.axis.variables:
                    if axis.kind == SearchAxis.CONFIGURATION:
                        targets[domain] = (position, variable, rows)
                    elif axis.kind == SearchAxis.VIRTUAL:
                        targets[variable] = (position, variable, rows)
                    elif domain == MAIN_DOMAIN:
                        targets[variable] = (position, variable, rows)
                        targets["config." + variable] = (position, variable, rows)
                        targets["main." + variable] = (position, variable, rows)
                    else:
                        targets["{0}.{1}".format(domain, variable)] = (position, variable, rows)
                position += 1
        self._pin_targets = targets
        return targets

    def feasible_size(self, limit=100000):
        """
        How many designs the space actually holds, once its exclusions are
        applied.

        Counted by walking the space, so it is only worth asking of a space
        small enough to walk: past `limit` genomes the count is what
        :meth:`size` says, since a search that large is never going to enumerate
        it anyway.

        Returns:
            tuple: the number of designs, and whether it was actually counted.
        """
        total = self.size()
        if not len(self.exclusions) or total > limit:
            return total, not len(self.exclusions)
        # Counted as designs, not as genomes: several genomes fold onto the one
        # configuration a "duplicate" says is the canonical one, and they are
        # that design rather than as many designs.
        found = set()
        for genome in self.genomes():
            design = self.design(genome)
            if design is not None:
                found.add(design.genome)
        return len(found), True

    def __repr__(self):
        return "<ArchitectureSpace {0} ({1} designs)>".format(self.name, self.size())


def _row_index(rows, variable, value):
    """
    Which row of an axis carries a given value of one of its variables.

    Both are read the way an expression reads them, so that "1" pins an axis
    that offers 1, and "On" one that offers On.
    """
    wanted = read_value(value)
    for index, row in enumerate(rows):
        if variable not in row:
            continue
        if read_value(row[variable]) == wanted:
            return index
    return None


class Design(object):
    """
    One design of the space: what to run, and what its parameters are.

    The configuration names are the identity -- they are what a run selects,
    what a work directory is called and what a result record carries -- and the
    values are what the search reasons about.
    """

    __slots__ = (
        "architecture", "genome", "configurations", "values", "frequency",
        "toolchain", "chose_toolchain", "contents",
    )

    def __init__(self, architecture, genome, configurations, values, frequency=None,
                 toolchain=None, chose_toolchain=False, contents=None):
        self.architecture = architecture
        self.genome = tuple(genome)
        #: What runs the design: the eda tool, its flow and its target. None
        #: when the exploration named no tool at all, which is what a workflow
        #: exploration looks like.
        self.toolchain = toolchain
        #: Whether the search is what picked it. A design run by the one
        #: toolchain the exploration was given still carries it -- it is where
        #: its results are read from -- but it is not what tells it apart from
        #: another design.
        self.chose_toolchain = bool(chose_toolchain)
        #: The frequency the design is synthesized at, in MHz, when the search
        #: chose it -- None when it did not, which is every run but a custom
        #: frequency synthesis exploring its frequencies.
        self.frequency = int(frequency) if frequency is not None else None
        #: ``{domain: configuration}``. The main domain is in there when the
        #: architecture has one; a design whose only axes are the variables of
        #: its commands has none, which is what an architecture that replaces
        #: nothing in its sources looks like.
        self.configurations = dict(configurations)
        #: ``{variable: value}``, named "<domain>.<variable>" outside the main
        #: domain, empty for a configuration written by hand.
        self.values = dict(values)
        #: ``{domain: content}``, what is written in each configuration, when it
        #: was at hand. Read by an "attributes" block, and by nothing else.
        self.contents = dict(contents or {})

    @property
    def configuration(self):
        """
        What names the design: the configuration of the main domain, or the
        architecture itself when it has none -- which is how Odatix has always
        named "the design with its parameters left alone".
        """
        return self.configurations.get(MAIN_DOMAIN) or self.architecture

    @property
    def entry(self):
        """
        What a run settings file selects to run this design::

            Counter/08bits+corner/tt

        The same thing a user writes by hand, which is what keeps an
        exploration from needing a run of its own kind: it fills in a selection
        and runs the command that was already there.
        """
        entry = self.architecture
        if MAIN_DOMAIN in self.configurations:
            entry += "/" + self.configurations[MAIN_DOMAIN]
        for domain in sorted(self.configurations):
            if domain != MAIN_DOMAIN:
                entry += "+{0}/{1}".format(domain, self.configurations[domain])
        return entry

    @property
    def label(self):
        """
        How the design is named to a user: what it selects, plus the frequency
        and the toolchain it was given when the search is the one that chose
        them.
        """
        label = self.entry
        if self.frequency is not None:
            label += " @ {0} MHz".format(self.frequency)
        if self.chose_toolchain and self.toolchain is not None:
            label += " [{0}]".format(self.toolchain.label)
        return label

    def __repr__(self):
        return "<Design {0}>".format(self.label)

    def __eq__(self, other):
        if not isinstance(other, Design):
            return NotImplemented
        return self.architecture == other.architecture and self.genome == other.genome

    def __ne__(self, other):
        result = self.__eq__(other)
        return result if result is NotImplemented else not result

    def __hash__(self):
        return hash((self.architecture, self.genome))
