# ********************************************************************** #
#                                Odatix                                  #
# ********************************************************************** #
#
# Copyright (C) 2022 Jonathan Saussereau
#
# This file is part of Odatix.
# Odatix is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Odatix is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Odatix. If not, see <https://www.gnu.org/licenses/>.
#

"""
Architectures: the designs a workspace runs its jobs on.

An architecture is a directory holding a settings file that says where the
design is, how it is built, and how its parameters are substituted, plus the
configurations of its parameter domains.
"""

import os

import odatix.lib.hard_settings as hard_settings
from odatix.workspace.configs import ConfigGeneration, combinations, count_combinations
from odatix.workspace.domains import ParameterDomain, ParameterDomainCollection
from odatix.workspace.entries import Collection, Entry
from odatix.workspace.settings import Setting, Settings

__all__ = [
    "FrequencyBounds",
    "CustomFrequencies",
    "ArchitectureSettings",
    "Architecture",
    "ArchitectureCollection",
]


######################################
# Settings
######################################

class FrequencyBounds(Settings):
    """
    The frequency range an fmax binary search runs in, in MHz.

    A bound left unset falls back to the workspace default, so only the bounds
    that are actually set are written.
    """

    lower_bound = Setting(None, type="optional_int", skip_if_empty=True, doc="Lowest frequency tried, in MHz.")
    upper_bound = Setting(None, type="optional_int", skip_if_empty=True, doc="Highest frequency tried, in MHz.")


class CustomFrequencies(Settings):
    """The frequencies a custom frequency synthesis runs at, in MHz."""

    frequencies = Setting(
        factory=list, type="int_list", key="list", style="flow", skip_if_empty=True,
        doc="Frequencies to synthesize at, in MHz.",
    )


class ArchitectureSettings(Settings):
    """
    Settings of an architecture ("<architecture>/_settings.yml"), which are also
    the settings of its main parameter domain.

    Frequency settings given per target (a mapping named after the target,
    holding its own "fmax_synthesis" and "custom_freq_synthesis" blocks) are not
    declared here, but they are preserved: like any other key Odatix does not
    know about, they stay in the file and in ``settings.extra``.
    """

    # RTL generation
    generate_rtl = Setting(
        False, type="bool", style="yesno", section="RTL generation",
        doc="Whether the RTL is generated by a command instead of read from a directory.",
    )
    design_path = Setting(
        "", type="str", when="generate_rtl",
        doc="Directory of the design sources the generation runs on.",
    )
    design_path_whitelist = Setting(
        factory=list, type="list", when="generate_rtl", style="flow",
        doc="What to copy from the design directory. Everything, when empty.",
    )
    design_path_blacklist = Setting(
        factory=list, type="list", when="generate_rtl", style="flow",
        doc="What not to copy from the design directory.",
    )
    generate_command = Setting("", type="str", when="generate_rtl", doc="Command that generates the RTL.")
    generate_output = Setting("", type="str", when="generate_rtl", doc="Directory the command writes the RTL to.")

    # Source files
    rtl_path = Setting(
        "", type="str", when="!generate_rtl", section="Source files",
        doc="Directory holding the RTL of the design.",
    )
    top_level_file = Setting("", type="str", doc="File holding the top level module.")
    top_level_module = Setting("", type="str", doc="Name of the top level module.")

    # Signals
    clock_signal = Setting("", type="str", section="Signals", doc="Name of the clock signal of the top level.")
    reset_signal = Setting("", type="str", doc="Name of the reset signal of the top level.")

    # Parameters
    use_parameters = Setting(
        False, type="bool", style="yesno", section="Delimiters for parameter files",
        doc="Whether the configurations of the main domain are substituted into a file.",
    )
    param_target_file = Setting(
        "", type="str", skip_if_empty=True,
        doc="File the parameters are written into. The top level file, when empty.",
    )
    start_delimiter = Setting("", type="str", doc="Text after which the parameters are written.")
    stop_delimiter = Setting("", type="str", doc="Text before which the parameters are written.")

    # Extra files copied into each work directory
    file_copy_enable = Setting(
        False, type="bool", style="yesno", skip_if_empty=True,
        doc="Whether an extra file is copied into each work directory.",
    )
    file_copy_source = Setting("", type="str", when="file_copy_enable", doc="File to copy.")
    file_copy_dest = Setting("", type="str", when="file_copy_enable", doc="Where to copy it, in the work directory.")

    # Frequencies
    fmax_synthesis = Setting(
        type=FrequencyBounds, section="Default frequencies (in MHz)", skip_if_empty=True,
        doc="Bounds of the fmax binary search for this architecture.",
    )
    custom_freq_synthesis = Setting(
        type=CustomFrequencies, skip_if_empty=True,
        doc="Frequencies a custom frequency synthesis runs this architecture at.",
    )

    # Configuration generation
    generate_configurations = Setting(
        False, type="bool", style="yesno", section="Configuration generation",
        doc="Whether the configurations of the main domain are generated from a template.",
    )
    generate_configurations_settings = Setting(
        type=ConfigGeneration, when="generate_configurations", skip_if_empty=True,
        doc="Template, name and variables the configurations are generated from.",
    )


######################################
# Architectures
######################################

class Architecture(Entry):
    """
    One architecture of a workspace.

    Its settings are those of its main parameter domain, so
    ``arch.settings`` and ``arch.domains.main.settings`` are the same object,
    and ``arch.configs`` are the configurations of that main domain.
    """

    kind = "architecture"

    #: Settings class of the main domain of this kind of instance.
    settings_class = ArchitectureSettings

    def __init__(self, workspace, root, name):
        super(Architecture, self).__init__(workspace, root, name)
        self._main = ParameterDomain(self, hard_settings.main_parameter_domain)

    ######################################
    # Settings
    ######################################

    @property
    def main_domain(self):
        """The parameter domain this architecture carries itself."""
        return self._main

    @property
    def settings_path(self):
        return self._main.settings_path

    @property
    def settings(self):
        """The settings of this architecture, read from file on first access."""
        return self._main.settings

    @settings.setter
    def settings(self, value):
        self._main.settings = value

    def reload(self):
        """Forget the settings held in memory and read them from file again."""
        self._main.reload()
        return self

    def save(self, regenerate=False):
        """Write the settings of this architecture back to its file."""
        self._main.save(regenerate=regenerate)
        return self

    def update(self, values=None, **kwargs):
        """Change some settings and write them back, in one call."""
        self.settings.update(values, **kwargs)
        return self.save()

    ######################################
    # Domains and configurations
    ######################################

    @property
    def domains(self):
        """The parameter domains of this architecture, the main one first."""
        return ParameterDomainCollection(self)

    @property
    def configs(self):
        """The configurations of the main parameter domain."""
        return self._main.configs

    def parameter_domains(self):
        """
        The configurations of every domain that actually uses parameters, as a
        ``{domain: [configuration, ...]}`` mapping. Domains that substitute
        nothing, and domains without configurations, are left out: they add no
        axis to the sweep.
        """
        result = {}
        for domain in self.domains:
            if not domain.use_parameters:
                continue
            names = domain.configs.names()
            if names:
                result[domain.name] = names
        return result

    def combinations(self):
        """
        Every configuration combination of this architecture, written the way a
        job selection names it.
        """
        return combinations(self.parameter_domains(), self.name)

    def count_combinations(self):
        """How many configuration combinations this architecture amounts to."""
        return count_combinations(self.parameter_domains())

    def generate_configurations(self, overwrite=False, clear=False, domains=None):
        """
        Generate the configurations of the domains that are set to generate
        them, and return what was written, as a ``{domain: [name, ...]}``
        mapping.

        Args:
            overwrite (bool): replace configurations that already exist.
            clear (bool): delete the existing configurations of a domain first.
            domains (list): restrict the generation to these domains.
        """
        written = {}
        for domain in self.domains:
            if domains is not None and domain.name not in domains:
                continue
            if not domain.settings.get("generate_configurations", False):
                continue
            names = domain.generate_configurations(overwrite=overwrite, clear=clear)
            if names:
                written[domain.name] = names
        return written


class ArchitectureCollection(Collection):
    """The architectures of a workspace."""

    entry_class = Architecture

    def _initialize(self, entry, **settings):
        if settings:
            entry.update(settings)
