
##############################################
# Settings for counter example
##############################################
---

rtl_path: "examples/counter_vhdl"

top_level_file: "counter.vhdl"
top_level_module: "counter"

clock_signal: "clock"
reset_signal: "reset"

# copy a file into synthesis directory?
file_copy_enable: No
file_copy_source: "/dev/null"
file_copy_dest: "/dev/null"

# delimiters for parameter files
use_parameters: Yes
start_delimiter: "generic ("
stop_delimiter: "  );"

# optional target-specific bounds (in MHz) to speed up fmax search
xc7s25-csga225-1:
  fmax_synthesis:
    lower_bound: 100
    upper_bound: 900
  custom_freq_synthesis:
    list: [50, 100]
xc7a100t-csg324-1:
  fmax_synthesis:
    lower_bound: 250
    upper_bound: 900
    architectures: # optional architecture-specific bounds
      04bits:
        lower_bound: 560
        upper_bound: 860
      08bits:
        lower_bound: 490
        upper_bound: 510
      16bits:
        lower_bound: 455
        upper_bound: 495
      24bits:
        lower_bound: 410
        upper_bound: 430
      32bits:
        lower_bound: 365
        upper_bound: 405
      48bits:
        lower_bound: 325
        upper_bound: 345
      64bits:
        lower_bound: 280
        upper_bound: 300
  custom_freq_synthesis:
    list: [50, 100]
xc7k70t-fbg676-2:
  fmax_synthesis:
    lower_bound: 200
    upper_bound: 1800
  custom_freq_synthesis:
    list: [50, 100]
XFAB180CMOS:
  fmax_synthesis:
    lower_bound: 400
    upper_bound: 700
  custom_freq_synthesis:
    list: [50, 100]
AMS350CMOS:
  fmax_synthesis:
    lower_bound: 60
    upper_bound: 160
  custom_freq_synthesis:
    list: [50, 100]
...
