
start_delimiter: "  // test parameters begin"
stop_delimiter: "  // test parameters end"

generate_configurations: Yes
generate_configurations_settings:
  template: "parameter VALUE = $var;"
  name: "config_${var}"
  variables:
    var:
      type: range
      settings:
        from: 10
        to: 100
        step: 10
