
##############################################
# Odatix settings for simulations
##############################################
---

# overwrite existing results
overwrite:        No   # overridden by -o / --overwrite

# prompt 'Continue? (Y/n)' after settings checks
ask_continue:     No   # overridden by -y / --noask

# exit monitor when all jobs are done
exit_when_done:   Yes  # overridden by -E / --exit

# size of the log history per job in the monitor
log_size_limit:   300  # overridden by --logsize

# maximum number of parallel jobs
nb_jobs:          8    # overridden by -j / --jobs

# targeted simulations
simulations: 

#--------------------------------------------#
# Add your own designs!
#--------------------------------------------#

  #- Your_Simulation:
  #  - Your_Design/Your_1st_Configuration
  #  - Your_Design/Your_2nd_Configuration
  #  - Your_Design/Your_3rd_Configuration

  # or 

  #- Your_Simulation:
  # - Your_Design/*

...
