// Generated by CIRCT firtool-1.58.0
module counter(
  input        clock,
               reset,
               i_init,
               i_inc_dec,
  output [7:0] o_value
);

  reg [7:0] value;
  always @(posedge clock) begin
    if (reset)
      value <= 8'h0;
    else if (i_init)
      value <= 8'h0;
    else if (i_inc_dec)
      value <= value + 8'h1;
    else
      value <= value - 8'h1;
  end // always @(posedge)
  assign o_value = value;
endmodule

