// Generated by CIRCT firtool-1.58.0
module top(
  input        clock,
               reset,
  output [8:0] o_data
);

  wire [7:0] _rom_o_data;
  wire [7:0] _counter_o_value;
  reg  [1:0] quadrant;
  wire       _counter_i_inc_dec_T = quadrant == 2'h0;
  wire       _counter_i_inc_dec_T_1 = quadrant == 2'h2;
  wire [7:0] _sin_val_T_1 = 8'h0 - _rom_o_data;
  wire       _GEN =
    (_counter_i_inc_dec_T | _counter_i_inc_dec_T_1) & (&_counter_o_value)
    | (quadrant == 2'h1 | (&quadrant)) & _counter_o_value == 8'h0;
  always @(posedge clock) begin
    if (reset)
      quadrant <= 2'h0;
    else if (_GEN) begin
      if (&quadrant)
        quadrant <= 2'h0;
      else
        quadrant <= quadrant + 2'h1;
    end
  end // always @(posedge)
  counter counter (
    .clock     (clock),
    .reset     (reset),
    .i_init    (_GEN),
    .i_inc_dec (_counter_i_inc_dec_T | _counter_i_inc_dec_T_1),
    .o_value   (_counter_o_value)
  );
  rom rom (
    .clock  (clock),
    .reset  (reset),
    .i_addr (_counter_o_value),
    .o_data (_rom_o_data)
  );
  assign o_data =
    _counter_i_inc_dec_T_1 | (&quadrant)
      ? {_sin_val_T_1[7], _sin_val_T_1}
      : {_rom_o_data[7], _rom_o_data};
endmodule

