
##############################################
# Settings for Shift Register example
##############################################
---

# generate the rtl (from chisel for example)
generate_rtl: Yes
generate_command: "sbt 'runMain ShiftRegister --o=rtl'" # this requires sbt and firtool

design_path: "examples/shift_register_chisel"
rtl_path: "examples/shift_register_chisel/rtl"

# generated design settings
top_level_file: "ShiftRegister.sv"
top_level_module: "ShiftRegister"
clock_signal: "clock"
reset_signal: "reset"

# copy a file into synthesis directory?
file_copy_enable: No
file_copy_source: "/dev/null"
file_copy_dest: "/dev/null"

# delimiters for parameter files
use_parameters: Yes
param_target_file: "src/main/scala/ShiftRegister.scala"
start_delimiter: "new ShiftRegister("
stop_delimiter: ")"

# optional target-specific bounds (in MHz) to speed up fmax search
xc7a100t-csg324-1:
  fmax_synthesis:
    lower_bound: 650
    upper_bound: 1000
  custom_freq_synthesis:
    list: [50, 100]
xc7k70t-fbg676-2:
  fmax_synthesis:
    lower_bound: 450
    upper_bound: 2500
  custom_freq_synthesis:
    list: [50, 100]
XFAB180CMOS:
  fmax_synthesis:
    lower_bound: 200
    upper_bound: 1000
  custom_freq_synthesis:
    list: [50, 100]
AMS350CMOS:
  fmax_synthesis:
    lower_bound: 50
    upper_bound: 500
  custom_freq_synthesis:
    list: [50, 100]
...
