# Design sources (that will be coppied into each work directory)
sources:
  path: examples/workflow_param_domains_cli
  # whitelist: 
  #   - "src/**"
  #   - "lib/**"
  #   - "config/**"
  blacklist:
    - "*.log"

# Progress tracking
progress:
  file: progress.txt
  regex: "Progress: ([0-9]+)"

# Generated design settings
use_parameters: No

# Design workflow settings
tasks:
  - name: main
    commands:
      - python3 simulate_traffic.py --max_speed ${max_speed} --num_vehicles ${num_vehicles} --signal_timing ${signal_timing} --road_length ${road_length}
