
start_delimiter: "  // test parameters begin"
stop_delimiter: "  // test parameters end"

generate_configurations: Yes
generate_configurations_settings:
  template: "parameter VALUE = $var;"
  name: "config_${var}"
  variables:
    var:
      type: power_of_two
      settings:
        from_2^: 5
        to_2^: 10
